
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "83d4b17273a641de7b68b3a3194ef856d3d9cd01",
 "version": "1.1.1+27.g83d4b17.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
